-- =============================================================
-- 阶段 13 · 英语题库（上）—— Unit 1~3（88 题）
-- 依据：docs/需求文档-英语题库.md 3.4 词汇表 / 3.5 常用表达（实体书照片核对）
--   Unit 1 Helping at home      课文 46，关卡 300~304（30 题）
--   Unit 2 My friends           课文 47，关卡 305~309（28 题）
--   Unit 3 Places we live in    课文 48，关卡 310~314（30 题）
-- 题型约定（与 QuestionValidator 一致）：
--   SINGLE：options 选项数组，answer = 正确选项下标（0 起）
--   JUDGE ：answer = true/false
--   BLANK ：answer = 可接受答案（数组）；判题自动忽略空格/标点/大小写
--   ORDER ：options 为待排序项，answer = 正确顺序的下标排列
-- 用法：mysql --default-character-set=utf8mb4 -uroot -p xxs_game < 51_english_questions_a.sql
-- 幂等性：重复导入前先 DELETE FROM question WHERE level_id BETWEEN 300 AND 314;
-- =============================================================

SET NAMES utf8mb4;
USE `xxs_game`;

-- =============================================================
-- Unit 1 Helping at home（lesson_id = 46）
-- =============================================================
INSERT INTO `question` (`lesson_id`, `level_id`, `type`, `stem`, `options`, `answer`, `analysis`, `knowledge_point`, `difficulty`, `sort_order`) VALUES
-- 第1关 职业与身份（level 300，6 题）
(46, 300, 'SINGLE', '"doctor" 的中文意思是（　）。',
 '["医生","老师","司机","农民"]', '0',
 'doctor 医生；老师 teacher，司机 driver，农民 farmer。', '职业词汇', 1, 1),
(46, 300, 'SINGLE', '"nurse" 的中文意思是（　）。',
 '["医生","护士","厨师","司机"]', '1',
 'nurse 护士；在医院照顾病人。', '职业词汇', 1, 2),
(46, 300, 'SINGLE', '"farmer" 的中文意思是（　）。',
 '["工人","农场主；农民","教师","医生"]', '1',
 'farmer 农场主；农民，在农场（farm）工作。', '职业词汇', 1, 3),
(46, 300, 'SINGLE', '"office worker" 的中文意思是（　）。',
 '["工厂工人","公司职员","快递员","消防队员"]', '1',
 'office 办公室 + worker 工人 → 公司职员；工厂工人是 factory worker。', '职业词汇', 2, 4),
(46, 300, 'JUDGE', '"factory worker" 的意思是"工厂工人"。',
 NULL, 'true',
 'factory 工厂 + worker 工人 → 工厂工人。', '职业词汇', 1, 5),
(46, 300, 'SINGLE', '"PE" 的中文意思是（　）。',
 '["数学（课）","体育（课）","英语（课）","音乐（课）"]', '1',
 'PE 是 Physical Education 的缩写，意思是体育（课）。', '职业词汇', 1, 6),

-- 第2关 家务劳动（level 301，6 题）
(46, 301, 'SINGLE', '"sweep the floor" 的中文意思是（　）。',
 '["擦窗户","扫地","铺床","洗碗"]', '1',
 'sweep 扫 + floor 地板 → 扫地。', '家务词汇', 1, 1),
(46, 301, 'JUDGE', '"look after" 的意思是"照顾"。',
 NULL, 'true',
 'look after 照顾，如 look after the children 照顾孩子们。', '家务词汇', 1, 2),
(46, 301, 'BLANK', '"家庭杂务"的英文是 c______（补全单词）。',
 NULL, '["chore","chores"]',
 'chore 家庭杂务，常用复数 chores，如 do some chores 做家务活。', '家务词汇', 2, 3),
(46, 301, 'JUDGE', '"clean" 既可以作动词表示"打扫"，也可以作形容词表示"干净的"。',
 NULL, 'true',
 'clean the room 打扫房间（动词）；a clean room 干净的房间（形容词）。', '家务词汇', 2, 4),
(46, 301, 'BLANK', '我们一起打扫房间：We clean the room ______（在一起；共同）。',
 NULL, '["together"]',
 'together 在一起；共同，放在句尾表示"一起做某事"。', '家务词汇', 3, 5),
(46, 301, 'JUDGE', '"My mother is busy and tired." 的意思是"我妈妈又忙又累"。',
 NULL, 'true',
 'busy 忙碌的，tired 疲倦的，and 连接两个形容词。', '家务词汇', 2, 6),

-- 第3关 核心句型（level 302，6 题）
(46, 302, 'SINGLE', '—What''s your mother''s job? —She''s a ______.',
 '["doctor","farmer","nurse","cook"]', '0',
 '问妈妈做什么工作，回答 She''s a/an + 职业，图片语境中为医生 doctor。', '常用表达', 1, 1),
(46, 302, 'SINGLE', '"What can we do for them?" 的中文意思是（　）。',
 '["他们在做什么？","我们能为他们做些什么？","他们是谁？","我们去哪里？"]', '1',
 'for them 为他们；整句：我们能为他们做些什么？', '常用表达', 2, 2),
(46, 302, 'ORDER', '连词成句：打扫房间',
 '["can","clean","We","the room","."] ', '[2,0,1,3,4]',
 'We can clean the room. 我们能打扫房间。', '常用表达', 3, 3),
(46, 302, 'SINGLE', '"What''s your mother''s job?" 是用来询问（　）。',
 '["妈妈的爱好","妈妈的名字","妈妈的职业","妈妈的年龄"]', '2',
 'job 工作；职业，问句询问的是职业。', '常用表达', 1, 4),
(46, 302, 'BLANK', '—What''s your father''s job? —He''s a ______. He works on a farm.',
 NULL, '["farmer"]',
 '在农场（farm）工作的是农民 farmer。', '常用表达', 2, 5),
(46, 302, 'JUDGE', '想询问别人妈妈的工作，可以说 "What''s your mother''s job?"。',
 NULL, 'true',
 'What''s your ... job? 是询问职业的常用句型。', '常用表达', 1, 6),

-- 第4关 语法与运用（level 303，6 题）
(46, 303, 'JUDGE', '"child" 的复数形式是 "children"。',
 NULL, 'true',
 'child 小孩的复数是不规则变化 children。', '语法运用', 2, 1),
(46, 303, 'SINGLE', '公园里有很多人：There are many ______ in the park.',
 '["people","child","peoples","childrens"]', '0',
 'many 后接可数名词复数；people 本身表示复数"人们"，不加 s。', '语法运用', 2, 2),
(46, 303, 'BLANK', '他的妈妈是医院里的一名护士：His mother is a ______ in the hospital.',
 NULL, '["nurse"]',
 'nurse 护士，在医院工作。', '语法运用', 2, 3),
(46, 303, 'JUDGE', '"Mum and Dad are busy and tired. We can do some chores." 表达正确。',
 NULL, 'true',
 '爸爸妈妈又忙又累，我们可以做一些家务活。', '语法运用', 1, 4),
(46, 303, 'SINGLE', '"job" 的中文意思是（　）。',
 '["游戏","工作；职业","故事","照片"]', '1',
 'job 工作；职业。game 游戏、story 故事、photo 照片是其他单元的词。', '语法运用', 1, 5),
(46, 303, 'ORDER', '连词成句：你妈妈的工作是什么',
 '["job","What''s","your","?","mother''s"]', '[1,2,4,0,3]',
 'What''s your mother''s job? 你妈妈做什么工作？', '常用表达', 3, 6),

-- 第5关 拼写挑战（level 304，6 题）
(46, 304, 'BLANK', '医生：d______（补全单词）',
 NULL, '["doctor"]',
 'doctor 医生。', '拼写', 2, 1),
(46, 304, 'BLANK', '护士：n______（补全单词）',
 NULL, '["nurse"]',
 'nurse 护士。', '拼写', 2, 2),
(46, 304, 'BLANK', '忙碌的：b____（补全单词）',
 NULL, '["busy"]',
 'busy 忙碌的。', '拼写', 2, 3),
(46, 304, 'BLANK', '疲倦的：t______（补全单词）',
 NULL, '["tired"]',
 'tired 疲倦的。', '拼写', 2, 4),
(46, 304, 'BLANK', '地板；地面：f______（补全单词）',
 NULL, '["floor"]',
 'floor 地板；地面。', '拼写', 3, 5),
(46, 304, 'BLANK', '照顾：look ______（补全词组）',
 NULL, '["after"]',
 'look after 照顾，固定词组搭配。', '拼写', 3, 6),

-- =============================================================
-- Unit 2 My friends（lesson_id = 47）
-- =============================================================
-- 第1关 外貌与性格（level 305，6 题）
(47, 305, 'SINGLE', '"strong" 的中文意思是（　）。',
 '["强壮的","文静的","友好的","疲倦的"]', '0',
 'strong 强壮的；He''s tall and strong. 他又高又壮。', '外貌性格', 1, 1),
(47, 305, 'SINGLE', '"文静的" 的英文是（　）。',
 '["quiet","kind","best","tired"]', '0',
 'quiet 文静的；kind 友好的，best 最好的。', '外貌性格', 2, 2),
(47, 305, 'SINGLE', '"kind" 的中文意思是（　）。',
 '["友好的","强壮的","最好的","强壮的"]', '0',
 'kind 友好的；He''s also kind. 他也很友善。', '外貌性格', 1, 3),
(47, 305, 'BLANK', '他又高又壮：He''s tall and ______.',
 NULL, '["strong"]',
 'tall and strong 又高又壮。', '外貌性格', 1, 4),
(47, 305, 'JUDGE', '"hair" 的意思是"头发"。',
 NULL, 'true',
 'hair 头发，是不可数名词，一般不加 s。', '外貌性格', 2, 5),
(47, 305, 'BLANK', '她的头发很长：Her ______ is long.',
 NULL, '["hair"]',
 'hair 头发。', '外貌性格', 2, 6),

-- 第2关 爱好与活动（level 306，6 题）
(47, 306, 'SINGLE', '"football" 的中文意思是（　）。',
 '["篮球运动","足球运动","排球运动","乒乓球运动"]', '1',
 'football 足球运动；篮球运动是 basketball。', '爱好活动', 1, 1),
(47, 306, 'JUDGE', '"basketball" 的意思是"篮球运动"。',
 NULL, 'true',
 'basketball 篮球运动，basket 篮 + ball 球。', '爱好活动', 1, 2),
(47, 306, 'SINGLE', '"阅读" 的英文是（　）。',
 '["read","play","buy","tell"]', '0',
 'read 阅读；play 玩耍，buy 购买，tell 讲述。', '爱好活动', 2, 3),
(47, 306, 'BLANK', '让我们踢足球吧：Let''s play ______.',
 NULL, '["football","soccer"]',
 'play football 踢足球；Let''s + 动词原形表示建议。', '爱好活动', 1, 4),
(47, 306, 'SINGLE', '"game" 的中文意思是（　）。',
 '["游戏","运动","故事","照片"]', '0',
 'game 游戏；play games 玩游戏。', '爱好活动', 1, 5),
(47, 306, 'ORDER', '连词成句：我经常玩游戏',
 '["often","I","play","games","."]', '[1,0,2,3,4]',
 'I often play games. often 频率副词放在实义动词前。', '爱好活动', 3, 6),

-- 第3关 朋友对话（level 307，6 题）
(47, 307, 'SINGLE', '—What''s your friend''s name? —______ name is Zhang Peng.',
 '["His","Her","Its","Their"]', '0',
 'Zhang Peng 是男孩，用 His 他的；His name is ... 他叫……', '常用表达', 2, 1),
(47, 307, 'SINGLE', '—Who''s your best friend? —______',
 '["Chen Jie. She''s funny.","I''m fine, thanks.","He''s a doctor.","It''s sunny today."]', '0',
 '问最好的朋友是谁，回答直接说名字和特点：陈杰，她很有趣。', '常用表达', 2, 2),
(47, 307, 'JUDGE', '"He''s also kind." 的意思是"他也很友好"。',
 NULL, 'true',
 'also 也；He''s also kind. 他也很友善。', '常用表达', 1, 3),
(47, 307, 'BLANK', '他经常帮助我：He ______ helps me.',
 NULL, '["often"]',
 'often 经常，频率副词放在实义动词 helps 前面。', '常用表达', 2, 4),
(47, 307, 'ORDER', '连词成句：他经常帮助我',
 '["helps","He","me","often","."]', '[1,3,0,2,4]',
 'He often helps me. 他经常帮助我。', '常用表达', 3, 5),
(47, 307, 'BLANK', '我最好的朋友：my ______ friend',
 NULL, '["best"]',
 'best 最好的；best friend 最好的朋友。', '常用表达', 2, 6),

-- 第4关 语法与运用（level 308，5 题）
(47, 308, 'JUDGE', '"his" 的意思是"他的"，后面接名词。',
 NULL, 'true',
 'his 他的（形容词性物主代词），如 his name 他的名字。', '语法运用', 2, 1),
(47, 308, 'SINGLE', '"always" 的中文意思是（　）。',
 '["总是","有时","从不","很少"]', '0',
 'always 总是，表示频率最高。', '语法运用', 1, 2),
(47, 308, 'SINGLE', '"Chinese" 不表示以下哪个意思（　）。',
 '["中文","中国人","体育","中国的"]', '2',
 'Chinese 可表示中文、中国人、中国的；体育是 PE。', '语法运用', 3, 3),
(47, 308, 'JUDGE', '用 "She''s funny." 形容一个女孩很有趣。',
 NULL, 'true',
 'funny 有趣的；She often makes me smile. 她经常让我开心。', '语法运用', 1, 4),
(47, 308, 'SINGLE', '______ name is Tom. He''s tall and strong.',
 '["His","Her","Its","Your"]', '0',
 'Tom 是男孩，用 His 他的。', '语法运用', 2, 5),

-- 第5关 拼写挑战（level 309，5 题）
(47, 309, 'BLANK', '强壮的：s______（补全单词）',
 NULL, '["strong"]',
 'strong 强壮的。', '拼写', 2, 1),
(47, 309, 'BLANK', '头发：h____（补全单词）',
 NULL, '["hair"]',
 'hair 头发。', '拼写', 2, 2),
(47, 309, 'BLANK', '文静的：q______（补全单词）',
 NULL, '["quiet"]',
 'quiet 文静的。', '拼写', 3, 3),
(47, 309, 'BLANK', '足球运动：f______（补全单词）',
 NULL, '["football"]',
 'football 足球运动。', '拼写', 2, 4),
(47, 309, 'BLANK', '篮球运动：b__________（补全单词）',
 NULL, '["basketball"]',
 'basketball 篮球运动。', '拼写', 3, 5),

-- =============================================================
-- Unit 3 Places we live in（lesson_id = 48）
-- =============================================================
-- 第1关 场所词汇（一）（level 310，6 题）
(48, 310, 'SINGLE', '"playground" 的中文意思是（　）。',
 '["游乐场；操场","图书馆","医院","公园"]', '0',
 'playground 游乐场；操场，play 玩 + ground 场地。', '场所词汇', 1, 1),
(48, 310, 'SINGLE', '"医院" 的英文是（　）。',
 '["hospital","library","park","shop"]', '0',
 'hospital 医院；library 图书馆，park 公园，shop 商店。', '场所词汇', 1, 2),
(48, 310, 'SINGLE', '"library" 的中文意思是（　）。',
 '["图书馆","体育馆","博物馆","商店"]', '0',
 'library 图书馆，可以借书、看书。', '场所词汇', 1, 3),
(48, 310, 'JUDGE', '"shop" 的意思是"商店"。',
 NULL, 'true',
 'shop 商店，买东西的地方；buy 购买。', '场所词汇', 1, 4),
(48, 310, 'BLANK', '公园：p____（补全单词）',
 NULL, '["park"]',
 'park 公园，可以在里面散步（walk）。', '场所词汇', 1, 5),
(48, 310, 'SINGLE', '"bus stop" 的中文意思是（　）。',
 '["公共汽车站","火车站","飞机场","地铁站"]', '0',
 'bus 公共汽车 + stop 停 → 公共汽车站。', '场所词汇', 2, 6),

-- 第2关 场所词汇（二）（level 311，6 题）
(48, 311, 'SINGLE', '"toilet" 的中文意思是（　）。',
 '["厕所；卫生间","图书馆","操场","商店"]', '0',
 'toilet 厕所；卫生间。', '场所词汇', 1, 1),
(48, 311, 'SINGLE', '"社区" 的英文是（　）。',
 '["community","afternoon","photo","story"]', '0',
 'community 社区，我们居住的地方。', '场所词汇', 2, 2),
(48, 311, 'JUDGE', '"favourite" 的意思是"最喜欢的"。',
 NULL, 'true',
 'favourite 最喜欢的；My favourite place is ... 我最喜欢的地方是……', '场所词汇', 2, 3),
(48, 311, 'BLANK', '我最喜欢的地方是博物馆：My ______ place is the museum.',
 NULL, '["favourite","favorite"]',
 'favourite 最喜欢的（英式拼写，美式为 favorite）。', '场所词汇', 2, 4),
(48, 311, 'SINGLE', '"photo" 的中文意思是（　）。',
 '["照片","故事","地方","照片馆"]', '0',
 'photo 照片；story 故事，place 地方。', '场所词汇', 1, 5),
(48, 311, 'SINGLE', '"story" 的中文意思是（　）。',
 '["故事","照片","图书馆","游戏"]', '0',
 'story 故事；storybook 故事书。', '场所词汇', 1, 6),

-- 第3关 There be 句型（level 312，6 题）
(48, 312, 'JUDGE', '"There is a playground." 的意思是"有一个游乐场"。',
 NULL, 'true',
 'There is + 单数名词，表示某处"有一个……"。', 'there be句型', 1, 1),
(48, 312, 'SINGLE', '那（这里）有个游乐场，我们经常在那里玩：______ ______ a playground. We often play there.',
 '["There is","There are","This is","These are"]', '0',
 'a playground 是单数，用 There is。', 'there be句型', 2, 2),
(48, 312, 'JUDGE', '"There are many people." 表示"这里有许多人"。',
 NULL, 'true',
 'There are + 复数名词；many people 许多人（people 本身是复数）。', 'there be句型', 2, 3),
(48, 312, 'SINGLE', '公园里有很多人：There ______ many people in the park.',
 '["are","is","be","am"]', '0',
 'many people 是复数概念，be 动词用 are。', 'there be句型', 2, 4),
(48, 312, 'BLANK', '这里还有一个体育馆：There is a ______ too.',
 NULL, '["gym"]',
 'gym 体育馆；too 也，放在句尾。', 'there be句型', 3, 5),
(48, 312, 'JUDGE', '"There is a taijiquan club." 的意思是"这里有一个太极拳俱乐部"。',
 NULL, 'true',
 'club 俱乐部；taijiquan club 太极拳俱乐部。', 'there be句型', 2, 6),

-- 第4关 问答与运用（level 313，6 题）
(48, 313, 'BLANK', '下午好，我们去公园散步吧：Good ______! Let''s walk in the park.',
 NULL, '["afternoon"]',
 'Good afternoon! 下午好；afternoon 下午。', '常用表达', 1, 1),
(48, 313, 'SINGLE', '"散步；行走" 的英文是（　）。',
 '["walk","play","read","fly"]', '0',
 'walk 散步；行走；fly 飞。', '常用表达', 2, 2),
(48, 313, 'BLANK', '太棒了！我们一起做运动吧：Great! Let''s do some ______.',
 NULL, '["sports"]',
 'do some sports 做运动；sport 体育运动。', '常用表达', 2, 3),
(48, 313, 'SINGLE', '"sport" 的中文意思是（　）。',
 '["体育运动","游戏","照片","社区"]', '0',
 'sport 体育运动；game 游戏。', '场所词汇', 1, 4),
(48, 313, 'JUDGE', '"buy" 的意思是"购买"，如 buy storybooks 买故事书。',
 NULL, 'true',
 'buy 购买；在商店（shop）里买东西用 buy。', '场所词汇', 2, 5),
(48, 313, 'ORDER', '连词成句：我最喜欢的地方是博物馆',
 '["is","favourite","My","the museum","place"]', '[2,1,4,0,3]',
 'My favourite place is the museum. 我最喜欢的地方是博物馆。', '常用表达', 3, 6),

-- 第5关 拼写挑战（level 314，6 题）
(48, 314, 'BLANK', '游乐场；操场：p__________（补全单词）',
 NULL, '["playground"]',
 'playground 游乐场；操场。', '拼写', 3, 1),
(48, 314, 'BLANK', '图书馆：l______（补全单词）',
 NULL, '["library"]',
 'library 图书馆。', '拼写', 2, 2),
(48, 314, 'BLANK', '医院：h______（补全单词）',
 NULL, '["hospital"]',
 'hospital 医院。', '拼写', 2, 3),
(48, 314, 'BLANK', '照片：p______（补全单词）',
 NULL, '["photo"]',
 'photo 照片。', '拼写', 2, 4),
(48, 314, 'BLANK', '下午：a________（补全单词）',
 NULL, '["afternoon"]',
 'afternoon 下午。', '拼写', 3, 5),
(48, 314, 'BLANK', '地方；场所：p______（补全单词）',
 NULL, '["place"]',
 'place 地方；场所。', '拼写', 2, 6);
