-- =============================================================
-- 阶段 13 · 英语题库（下）—— Unit 4~6 + Revision（106 题）
-- 依据：docs/需求文档-英语题库.md 3.4 词汇表 / 3.5 常用表达（实体书照片核对）
--   Unit 4 Helping in the community    课文 49，关卡 315~319（28 题）
--   Unit 5 The weather and us          课文 50，关卡 320~325（34 题）
--   Unit 6 Changing for the seasons    课文 51，关卡 326~330（32 题）
--   Revision Let's help!               课文 52，关卡 331~332（12 题，复习前 6 单元重点）
-- 题型约定（与 QuestionValidator 一致）：
--   SINGLE：options 选项数组，answer = 正确选项下标（0 起）
--   JUDGE ：answer = true/false
--   BLANK ：answer = 可接受答案（数组）；判题自动忽略空格/标点/大小写
--   ORDER ：options 为待排序项，answer = 正确顺序的下标排列
-- 用法：mysql --default-character-set=utf8mb4 -uroot -p xxs_game < 52_english_questions_b.sql
-- 幂等性：重复导入前先 DELETE FROM question WHERE level_id BETWEEN 315 AND 332;
-- =============================================================

SET NAMES utf8mb4;
USE `xxs_game`;

-- =============================================================
-- Unit 4 Helping in the community（lesson_id = 49）
-- =============================================================
INSERT INTO `question` (`lesson_id`, `level_id`, `type`, `stem`, `options`, `answer`, `analysis`, `knowledge_point`, `difficulty`, `sort_order`) VALUES
-- 第1关 社区职业（level 315，6 题）
(49, 315, 'SINGLE', '"firefighter" 的中文意思是（　）。',
 '["快递员","消防队员","清洁工","司机"]', '1',
 'firefighter 消防队员；fire 火 + fighter 战斗者。', '职业词汇', 1, 1),
(49, 315, 'SINGLE', '"delivery worker" 的中文意思是（　）。',
 '["消防队员","快递员","清洁工","警察"]', '1',
 'delivery worker 快递员，负责送包裹。', '职业词汇', 1, 2),
(49, 315, 'JUDGE', '"police officer" 的意思是"警察；警员"。',
 NULL, 'true',
 'police officer 警察；警员，维护社区安全。', '职业词汇', 1, 3),
(49, 315, 'SINGLE', '"清洁工" 的英文是（　）。',
 '["cleaner","cook","driver","doctor"]', '0',
 'cleaner 清洁工，由 clean（打扫）加 -er 构成。', '职业词汇', 2, 4),
(49, 315, 'BLANK', '司机：d______（补全单词）',
 NULL, '["driver"]',
 'driver 司机，drive 开车 + -er。', '职业词汇', 2, 5),
(49, 315, 'SINGLE', '"cook" 作名词时的意思是（　）。',
 '["烹饪","厨师","打扫","护士"]', '1',
 'cook 动词"烹饪；煮"（Unit 1），名词"厨师"（Unit 4）。', '职业词汇', 2, 6),

-- 第2关 工作与帮助（level 316，6 题）
(49, 316, 'JUDGE', '"Our neighbour is a firefighter. He often helps people." 表达正确：我们的邻居是消防员，他经常帮助别人。',
 NULL, 'true',
 'neighbour 邻居；often 表示"经常"。', '常用表达', 1, 1),
(49, 316, 'SINGLE', '他是校车司机，每天送我们去上学：He''s a school bus ______. He takes us to school every day.',
 '["driver","cleaner","officer","worker"]', '0',
 'school bus driver 校车司机。', '常用表达', 2, 2),
(49, 316, 'BLANK', '那个工作也很重要：That''s an ______ job too!',
 NULL, '["important"]',
 'important 重要的，元音音素开头用 an。', '常用表达', 2, 3),
(49, 316, 'JUDGE', '"Ms" 用于女子的姓氏或姓名前，不指明婚否。',
 NULL, 'true',
 'Ms 女士，如 Ms Green 格林女士。', '常用表达', 2, 4),
(49, 316, 'SINGLE', '"why" 的中文意思是（　）。',
 '["什么","为什么","谁","哪里"]', '1',
 'why 为什么，用来询问原因。', '职业词汇', 1, 5),
(49, 316, 'ORDER', '连词成句：他经常帮助人们',
 '["helps","He","people","often","."]', '[1,3,0,2,4]',
 'He often helps people. 他经常帮助人们。', '常用表达', 3, 6),

-- 第3关 句型与对话（level 317，6 题）
(49, 317, 'SINGLE', '"Why do you like your job?" 中 "why" 询问的是（　）。',
 '["时间","原因","地点","人物"]', '1',
 'why 为什么，用来询问原因。', '语法运用', 2, 1),
(49, 317, 'ORDER', '连词成句：陈杰正在铺床',
 '["is","Chen Jie","the bed","making","."]', '[1,0,3,2,4]',
 'Chen Jie is making the bed. 陈杰正在铺床。', '常用表达', 3, 2),
(49, 317, 'JUDGE', '"make the bed" 的意思是"铺床"。',
 NULL, 'true',
 'make the bed 铺床，固定词组。', '家务词汇', 1, 3),
(49, 317, 'SINGLE', '我们的邻居是消防员：______ neighbour is a firefighter.',
 '["Our","We","Us","Ours"]', '0',
 'Our 我们的（形容词性物主代词），后面接名词 neighbour。', '语法运用', 2, 4),
(49, 317, 'BLANK', '在幼儿园，约翰和一班的孩子们在一起唱歌：In the kindergarten, John and Class One are ______ songs together.',
 NULL, '["singing"]',
 'sing 唱歌，现在进行时用 singing。', '常用表达', 3, 5),
(49, 317, 'ORDER', '连词成句：那也是一个重要的工作',
 '["important","That''s","too","an","job","."]', '[1,3,0,4,2,5]',
 'That''s an important job too! 那个工作也很重要！', '常用表达', 3, 6),

-- 第4关 现在进行时（level 318，5 题）
(49, 318, 'JUDGE', '"Chen Jie is making the bed." 用的是现在进行时。',
 NULL, 'true',
 'is + making 表示"正在铺床"，动作正在进行。', '语法运用', 2, 1),
(49, 318, 'SINGLE', '现在进行时的基本结构是（　）。',
 '["be动词 + 动词ing","do + 动词原形","is + 动词原形","can + 动词ing"]', '0',
 '现在进行时 = be 动词（am/is/are）+ 动词的 ing 形式。', '语法运用', 3, 2),
(49, 318, 'BLANK', 'Look! The children ______ singing songs together.',
 NULL, '["are"]',
 'children 是复数，be 动词用 are。', '语法运用', 2, 3),
(49, 318, 'ORDER', '连词成句：我们现在正在铺床',
 '["We","making","the bed","are","now","."]', '[0,3,1,2,4,5]',
 'We are making the bed now. 我们现在正在铺床。', '语法运用', 3, 4),
(49, 318, 'JUDGE', '"a lot of" 的意思是"大量；许多"。',
 NULL, 'true',
 'a lot of 大量；许多，后接可数或不可数名词。', '常用表达', 1, 5),

-- 第5关 拼写挑战（level 319，5 题）
(49, 319, 'BLANK', '消防队员：f__________（补全单词）',
 NULL, '["firefighter"]',
 'firefighter 消防队员。', '拼写', 3, 1),
(49, 319, 'BLANK', '司机：d______（补全单词）',
 NULL, '["driver"]',
 'driver 司机。', '拼写', 2, 2),
(49, 319, 'BLANK', '重要的：i________（补全单词）',
 NULL, '["important"]',
 'important 重要的。', '拼写', 3, 3),
(49, 319, 'BLANK', '现在：n__（补全单词）',
 NULL, '["now"]',
 'now 现在。', '拼写', 1, 4),
(49, 319, 'BLANK', '每人：e_______（补全单词）',
 NULL, '["everyone"]',
 'everyone 每人，人人。', '拼写', 2, 5),

-- =============================================================
-- Unit 5 The weather and us（lesson_id = 50）
-- =============================================================
-- 第1关 天气词汇（一）（level 320，6 题）
(50, 320, 'SINGLE', '"sunny" 的中文意思是（　）。',
 '["下雨的","阳光充足的；晴朗的","多云的","多风的"]', '1',
 'sunny 阳光充足的；晴朗的，sun 太阳 + ny。', '天气词汇', 1, 1),
(50, 320, 'SINGLE', '"多云的" 的英文是（　）。',
 '["sunny","windy","cloudy","rainy"]', '2',
 'cloudy 多云的，cloud 云。', '天气词汇', 1, 2),
(50, 320, 'JUDGE', '"windy" 的意思是"多风的"。',
 NULL, 'true',
 'windy 多风的，wind 风。', '天气词汇', 1, 3),
(50, 320, 'BLANK', '热的：h__（补全单词）',
 NULL, '["hot"]',
 'hot 热的。', '天气词汇', 1, 4),
(50, 320, 'SINGLE', '"cold" 的中文意思是（　）。',
 '["热的","温暖的","冷的","凉爽的"]', '2',
 'cold 冷的；hot 热、warm 温暖、cool 凉爽。', '天气词汇', 1, 5),
(50, 320, 'BLANK', '凉爽的：c____（补全单词）',
 NULL, '["cool"]',
 'cool 凉爽的。', '天气词汇', 2, 6),

-- 第2关 天气词汇（二）（level 321，6 题）
(50, 321, 'SINGLE', '"rainy" 的中文意思是（　）。',
 '["阴雨的","晴朗的","多雪的","多云的"]', '0',
 'rainy 阴雨的，rain 雨。', '天气词汇', 1, 1),
(50, 321, 'JUDGE', '"snowy" 的意思是"多雪的"。',
 NULL, 'true',
 'snowy 多雪的，snow 雪。', '天气词汇', 1, 2),
(50, 321, 'BLANK', '温暖的：w____（补全单词）',
 NULL, '["warm"]',
 'warm 温暖的。', '天气词汇', 2, 3),
(50, 321, 'SINGLE', '"Sydney" 是一个（　）。',
 '["国家","城市","季节","人物"]', '1',
 'Sydney 悉尼，澳大利亚的城市。', '天气词汇', 1, 4),
(50, 321, 'BLANK', '下雨；雨：r___（补全单词）',
 NULL, '["rain"]',
 'rain 下雨（动词）；雨（名词）。', '天气词汇', 2, 5),
(50, 321, 'SINGLE', '"closed" 的中文意思是（　）。',
 '["打开的","关闭的","新的","旧的"]', '1',
 'closed 关闭的；图书馆关门了用 The library is closed.', '天气词汇', 2, 6),

-- 第3关 天气问答（level 322，6 题）
(50, 322, 'SINGLE', '—What''s the weather like in Sydney? —______',
 '["Well, it''s sunny today.","It''s a book.","She''s a nurse.","It''s Monday."]', '0',
 '问天气怎么样，回答用 it''s + 天气词：今天是晴天。', '常用表达', 2, 1),
(50, 322, 'JUDGE', '电话用语 "Hello! Mark speaking." 的意思是"你好！我是马克。"',
 NULL, 'true',
 '打电话时介绍自己用 This is ... / ... speaking。', '常用表达', 2, 2),
(50, 322, 'BLANK', '嗨，马克！我是约翰：Hi, Mark! ______ is John.',
 NULL, '["This"]',
 '打电话时说"我是约翰"用 This is John.，不用 I am。', '常用表达', 2, 3),
(50, 322, 'JUDGE', '现在下雨了：It''s raining now. 表达正确。',
 NULL, 'true',
 'It''s raining now. 现在正在下雨。', '常用表达', 1, 4),
(50, 322, 'ORDER', '连词成句：悉尼的天气怎么样',
 '["What''s","weather","the","like","in Sydney","?"]', '[0,2,1,3,4,5]',
 'What''s the weather like in Sydney? 悉尼的天气怎么样？', '常用表达', 3, 5),
(50, 322, 'SINGLE', '北京只有两度：It''s only two ______ in Beijing.',
 '["degrees","photos","ideas","seasons"]', '0',
 'degree 度，two 后面用复数 degrees。', '常用表达', 3, 6),

-- 第4关 活动与安排（level 323，6 题）
(50, 323, 'SINGLE', '我们不能在公园打篮球了：We ______ play basketball in the park.',
 '["can","can''t","do","don''t"]', '1',
 'can''t = cannot，不能；下雨了所以不能打篮球。', '常用表达', 2, 1),
(50, 323, 'BLANK', '没关系，我们可以去图书馆：It''s OK. We can go to the ______.',
 NULL, '["library"]',
 '下雨天可以去图书馆（library）。', '常用表达', 1, 2),
(50, 323, 'SINGLE', '"film" 的中文意思是（　）。',
 '["游戏","电影","故事","主意"]', '1',
 'film 电影；go to the films 去看电影。', '常用表达', 1, 3),
(50, 323, 'BLANK', '想法；主意：i____（补全单词）',
 NULL, '["idea"]',
 'idea 想法；主意，Good idea! 好主意！', '常用表达', 2, 4),
(50, 323, 'JUDGE', '"Let''s fly a kite tomorrow." 的意思是"我们明天去放风筝吧"。',
 NULL, 'true',
 'fly a kite 放风筝；tomorrow 明天。', '常用表达', 2, 5),
(50, 323, 'SINGLE', '明天见：See you ______.',
 '["yesterday","today","tomorrow","now"]', '2',
 'tomorrow 在明天；yesterday 昨天，today 今天。', '常用表达', 2, 6),

-- 第5关 四季与活动（level 324，5 题）
(50, 324, 'BLANK', '我们堆雪人吧：Let''s make a ______!',
 NULL, '["snowman"]',
 'snowman 雪人，snow 雪 + man 人。', '天气词汇', 2, 1),
(50, 324, 'JUDGE', '"Their children swim in the pool." 的意思是"他们的孩子在泳池里游泳"。',
 NULL, 'true',
 'their 他们的；swim 游泳；pool 泳池。', '常用表达', 1, 2),
(50, 324, 'BLANK', '他们的：t______（补全单词）',
 NULL, '["their"]',
 'their 他们的；她们的；它们的。', '语法运用', 2, 3),
(50, 324, 'SINGLE', '"kite" 的中文意思是（　）。',
 '["风筝","电影","主意","乐趣"]', '0',
 'kite 风筝；fly a kite 放风筝。', '天气词汇', 1, 4),
(50, 324, 'SINGLE', '这里很热，是个大晴天：It''s hot and ______ here.',
 '["cloudy","sunny","snowy","windy"]', '1',
 'hot and sunny 又热又晴。', '天气词汇', 1, 5),

-- 第6关 拼写挑战（level 325，5 题）
(50, 325, 'BLANK', '天气：w______（补全单词）',
 NULL, '["weather"]',
 'weather 天气。', '拼写', 3, 1),
(50, 325, 'BLANK', '阳光充足的：s____（补全单词）',
 NULL, '["sunny"]',
 'sunny 阳光充足的。', '拼写', 2, 2),
(50, 325, 'BLANK', '多风的：w____（补全单词）',
 NULL, '["windy"]',
 'windy 多风的。', '拼写', 2, 3),
(50, 325, 'BLANK', '明天：t________（补全单词）',
 NULL, '["tomorrow"]',
 'tomorrow 明天。', '拼写', 3, 4),
(50, 325, 'BLANK', '风筝：k___（补全单词）',
 NULL, '["kite"]',
 'kite 风筝。', '拼写', 1, 5),

-- =============================================================
-- Unit 6 Changing for the seasons（lesson_id = 51）
-- =============================================================
-- 第1关 服装词汇（level 326，7 题）
(51, 326, 'SINGLE', '"sweater" 的中文意思是（　）。',
 '["衬衫","毛衣","连衣裙","外套"]', '1',
 'sweater 毛衣。', '服装词汇', 1, 1),
(51, 326, 'SINGLE', '"连衣裙" 的英文是（　）。',
 '["dress","shirt","coat","sock"]', '0',
 'dress 连衣裙；shirt 衬衫，coat 大衣，sock 短袜。', '服装词汇', 1, 2),
(51, 326, 'JUDGE', '"shirt" 的意思是"衬衫"。',
 NULL, 'true',
 'shirt 衬衫。', '服装词汇', 1, 3),
(51, 326, 'BLANK', '大衣；外套：c___（补全单词）',
 NULL, '["coat"]',
 'coat 大衣；外套，冬天穿。', '服装词汇', 1, 4),
(51, 326, 'SINGLE', '"T-shirt" 的中文意思是（　）。',
 '["毛衣","T恤衫","短袜","手套"]', '1',
 'T-shirt T恤衫。', '服装词汇', 1, 5),
(51, 326, 'BLANK', '短袜：s___（补全单词）',
 NULL, '["sock"]',
 'sock 短袜，通常用复数 socks。', '服装词汇', 1, 6),
(51, 326, 'SINGLE', '"手套" 的英文是（　）。',
 '["glove","shirt","sweater","dress"]', '0',
 'glove 手套，通常用复数 gloves。', '服装词汇', 2, 7),

-- 第2关 季节词汇（level 327，7 题）
(51, 327, 'SINGLE', '"季节" 的英文是（　）。',
 '["season","winter","spring","autumn"]', '0',
 'season 季节；一年有四个季节（four seasons）。', '季节词汇', 1, 1),
(51, 327, 'SINGLE', '"winter" 的中文意思是（　）。',
 '["春天","夏天","秋天","冬天"]', '3',
 'winter 冬天；spring 春天，summer 夏天，autumn 秋天。', '季节词汇', 1, 2),
(51, 327, 'JUDGE', '"spring" 是春天，"autumn" 是秋天。',
 NULL, 'true',
 'spring 春天、summer 夏天、autumn 秋天、winter 冬天。', '季节词汇', 1, 3),
(51, 327, 'BLANK', '夏天：s______（补全单词）',
 NULL, '["summer"]',
 'summer 夏天，一年中最热的季节。', '季节词汇', 2, 4),
(51, 327, 'SINGLE', '秋天，树叶从树上落下来：In autumn, ______ fall from the trees.',
 '["leaf","leaves","leafs","leafes"]', '1',
 'leaf 的复数是不规则变化 leaves。', '季节词汇', 3, 5),
(51, 327, 'SINGLE', '"snow" 可以表示（　）。',
 '["只有名词“雪”","只有动词“下雪”","动词“下雪”和名词“雪”","形容词“雪白的”"]', '2',
 'snow 下雪（动词）；雪（名词），如 It snows a lot. 经常下雪。', '季节词汇', 2, 6),
(51, 327, 'JUDGE', '"get together" 的意思是"聚会"。',
 NULL, 'true',
 'get together 聚会；家人冬天聚会。', '季节词汇', 2, 7),

-- 第3关 Whose 与 Which（level 328，6 题）
(51, 328, 'SINGLE', '—Whose sweater is this, Mum? —______',
 '["It''s your dad''s.","It''s sunny.","He''s a doctor.","It''s cold."]', '0',
 '问"这是谁的毛衣"，回答：它是你爸爸的。', '常用表达', 2, 1),
(51, 328, 'JUDGE', '"whose" 的意思是"谁的"。',
 NULL, 'true',
 'whose 谁的，用来询问物品的主人。', '语法运用', 1, 2),
(51, 328, 'SINGLE', '______ season do you like?',
 '["Which","Whose","What","Where"]', '0',
 'Which season 哪个季节，表示在一定范围内选择。', '语法运用', 2, 3),
(51, 328, 'BLANK', '我今天可以穿这件新衬衫吗：Can I ______ this new shirt today?',
 NULL, '["wear"]',
 'wear 穿；戴。', '常用表达', 1, 4),
(51, 328, 'SINGLE', '—Which season do you like? —______. It snows a lot.',
 '["Spring","Winter","Autumn","Summer"]', '1',
 '后面说"经常下雪"，所以是冬天 Winter。', '常用表达', 2, 5),
(51, 328, 'JUDGE', '"Can I wear this new shirt today?" 是一句请求许可的问句。',
 NULL, 'true',
 'Can I ...? 用来请求许可："我可以……吗？"。', '语法运用', 2, 6),

-- 第4关 季节对话（level 329，6 题）
(51, 329, 'SINGLE', '可以，但是再穿一件外套吧，外面有风又很冷：Yes, but wear a coat too. It''s cold and ______ outside.',
 '["sunny","windy","hot","warm"]', '1',
 'windy 多风的；cold and windy 又冷又有风。', '常用表达', 2, 1),
(51, 329, 'BLANK', '我也喜欢冬天，有很多节日：I like winter too. There are many ______.',
 NULL, '["festivals"]',
 'festival 节日，many 后接复数 festivals。', '常用表达', 3, 2),
(51, 329, 'ORDER', '连词成句：这是谁的毛衣',
 '["sweater","Whose","this","is","?"]', '[1,0,3,2,4]',
 'Whose sweater is this? 这是谁的毛衣？', '常用表达', 2, 3),
(51, 329, 'JUDGE', '"It''s full of life." 的意思是"（春天）充满生机"。',
 NULL, 'true',
 'full of life 充满生机，描述春天万物生长。', '常用表达', 2, 4),
(51, 329, 'BLANK', '然后，春天又来了：______ spring comes again.',
 NULL, '["Then"]',
 'Then 然后；那时，放在句首。', '常用表达', 2, 5),
(51, 329, 'ORDER', '连词成句：你喜欢哪个季节',
 '["Which","do","season","you","like","?"]', '[0,2,3,1,4,5]',
 'Which season do you like? 你喜欢哪个季节？', '常用表达', 3, 6),

-- 第5关 拼写挑战（level 330，6 题）
(51, 330, 'BLANK', '毛衣：s______（补全单词）',
 NULL, '["sweater"]',
 'sweater 毛衣。', '拼写', 2, 1),
(51, 330, 'BLANK', '衬衫：s______（补全单词）',
 NULL, '["shirt"]',
 'shirt 衬衫。', '拼写', 2, 2),
(51, 330, 'BLANK', '冬天：w______（补全单词）',
 NULL, '["winter"]',
 'winter 冬天。', '拼写', 1, 3),
(51, 330, 'BLANK', '春天：s______（补全单词）',
 NULL, '["spring"]',
 'spring 春天。', '拼写', 1, 4),
(51, 330, 'BLANK', '秋天：a_____（补全单词）',
 NULL, '["autumn"]',
 'autumn 秋天。', '拼写', 2, 5),
(51, 330, 'BLANK', '季节：s______（补全单词）',
 NULL, '["season"]',
 'season 季节。', '拼写', 1, 6),

-- =============================================================
-- Revision Let's help!（lesson_id = 52，复习前 6 单元重点）
-- =============================================================
-- 第1关 综合复习（一）（level 331，6 题：复习 Unit 1~3）
(52, 331, 'SINGLE', '—What''s your mother''s job? —She''s a ______.',
 '["doctor","winter","library","floor"]', '0',
 '回答职业：She''s a doctor. 她是医生。（复习 Unit 1）', '职业词汇', 1, 1),
(52, 331, 'BLANK', '我们可以做一些家务活：We can do some ______.',
 NULL, '["chores"]',
 'do some chores 做家务活。（复习 Unit 1）', '家务词汇', 2, 2),
(52, 331, 'SINGLE', '—Who''s your best friend? —Zhang Peng. He''s ______ and strong.',
 '["tall","quiet","busy","old"]', '0',
 'He''s tall and strong. 他又高又壮。（复习 Unit 2）', '外貌性格', 2, 3),
(52, 331, 'JUDGE', '"He''s also kind. He often helps me." 的意思是"他也很友善，他经常帮助我"。',
 NULL, 'true',
 'also 也；kind 友好的。（复习 Unit 2）', '常用表达', 1, 4),
(52, 331, 'SINGLE', '图书馆（library）是一个（　）。',
 '["职业","场所","季节","天气"]', '1',
 'library 图书馆是场所（place）。（复习 Unit 3）', '场所词汇', 1, 5),
(52, 331, 'ORDER', '连词成句：我最喜欢的地方是博物馆',
 '["My","is","place","favourite","the museum","."]', '[0,3,2,1,4,5]',
 'My favourite place is the museum.（复习 Unit 3）', '常用表达', 3, 6),

-- 第2关 综合复习（二）（level 332，6 题：复习 Unit 4~6）
(52, 332, 'SINGLE', '我们的邻居是消防员，他经常帮助人们：Our neighbour is a firefighter. He often ______ people.',
 '["help","helps","helping","helped"]', '1',
 '主语 He 是第三人称单数，often 后动词加 s：helps。（复习 Unit 4）', '语法运用', 3, 1),
(52, 332, 'BLANK', '陈杰正在铺床：Chen Jie is making the ______.',
 NULL, '["bed"]',
 'make the bed 铺床。（复习 Unit 4）', '常用表达', 2, 2),
(52, 332, 'SINGLE', '—今天天气怎么样？—______ 让我们放风筝吧！',
 '["It''s sunny.","It''s snowing.","It''s rainy.","It''s windy."]', '0',
 '晴天适合放风筝：It''s sunny.（复习 Unit 5）', '天气词汇', 1, 3),
(52, 332, 'JUDGE', '"It''s raining now. We can''t play basketball in the park." 的意思是"现在下雨了，我们不能在公园打篮球了"。',
 NULL, 'true',
 'can''t = cannot 不能。（复习 Unit 5）', '常用表达', 1, 4),
(52, 332, 'SINGLE', '—这件大衣是谁的？—______',
 '["It''s your dad''s.","It''s your dad.","They''re your dad''s.","It''s a coat dad."]', '0',
 'Whose 问主人，回答用 It''s + 人物''s。（复习 Unit 6）', '常用表达', 2, 5),
(52, 332, 'ORDER', '连词成句：你妈妈做什么工作',
 '["job","What''s","your","mother''s","?"]', '[1,2,3,0,4]',
 'What''s your mother''s job?（复习 Unit 1，词汇句型综合）', '常用表达', 2, 6);
